# Generated by Django 4.2 on 2024-06-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_control', '0002_alter_child_mobile_phone_alter_document_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='data_end',
            field=models.DateField(blank=True, default=0, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price_with_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
