# Generated by Django 4.2 on 2024-06-07 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit_control', '0003_alter_subscription_data_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Чат айди тг бота'),
        ),
        migrations.AlterField(
            model_name='group',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='visit_control.employee'),
        ),
    ]
