# Generated by Django 4.2 on 2024-06-11 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit_control', '0005_alter_subscription_document'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='document',
        ),
        migrations.AlterModelTable(
            name='sale',
            table='sale',
        ),
    ]
